### ISSUE TITLE
[Request]: Realtime Load Testing ActiveMQ

### ISSUE THREAD

**Issue by logeshk** [QAInsights/Blog-YouTube-Requests#5]
### Contact Details

logeshkumarvb@gmail.com

### Tutorial Type

YouTube

### Please list out the technologies or tools involved.

Realtime Load Testing ActiveMQ

### Is your tutorial request related to a problem?

Realtime Load Testing ActiveMQ

### Sponsor

Yes

**Comment by QAInsights** [comment]
Is this tutorial not helping you? https://youtu.be/4S8VpMeOVPc @logeshk

**Comment by logeshk** [comment]
@QAInsights Its helpful, now I am approaching aligining according product architecture. Thanks Naveen
